### ISSUE TITLE
Manageable Actions in ML Pipelines

### ISSUE THREAD

**Issue by remcollier** [w3c-cg/webagents#23]
One scenario in which manageable actions can arise is agent-based monitoring and orchestration of ML pipelines.  This can be considered in a number of scenarios:

- The ML Pipeline is a black box whose execution the agent is overseeing (for example - a report of suspected illegal fishing activity in the Irish sea could trigger a ship detection model that uses remote sensing satelite data to locate and track the movement of ships in a given area.  The overall model could take some time to run (tile download, model exection, processing of results).

- The second scenario could relate to the monitoring of the quality of the model. In the event that the model drops below a required quality (model drift), the agent could trigger a retraining phase which would be another example of a long running action).

- When applied to the orchestration of a ML Pipeline itself (so inside the black box), the agent would be responsible for preparing and executing the different tasks within the pipeline. Individual tasks could take some time, and awareness of progress could be used to prepare the next task so that it is readly as soon as the current task is completed while miminising cloud resource usage. Each individual task would be a potentially long running action that would need to be managed.

**Comment by andreiciortea** [comment]
(scenario resubmitted via Issue #24)
